_data		segment	para public 'DATA' use32

aWt_1:
		unicode	0, <wt>,0
aConstT_bincmdB	db 'const t_bincmd bincmd[] = {',0Ah,0
aTS				db 0Ah,'  { T("%S"),',0Ah,0
aD_cmd		db 'D_CMD',0
aD_mov		db 'D_MOV',0
aD_movc		db 'D_MOVC',0
aD_setc		db 'D_SETC',0
aD_test		db 'D_TEST',0
aD_string	db 'D_STRING',0
aD_jmp		db 'D_JMP',0
aD_jmpfar	db 'D_JMPFAR',0
aD_jmc		db 'D_JMC',0
aD_jmcx		db 'D_JMCX',0
aD_push		db 'D_PUSH',0
aD_pop		db 'D_POP',0
aD_call		db 'D_CALL',0
aD_callfar	db 'D_CALLFAR',0
aD_int		db 'D_INT',0
aD_ret		db 'D_RET',0
aD_retfar	db 'D_RETFAR',0
aD_fpu		db 'D_FPU',0
aD_mmx		db 'D_MMX',0
aD_3dnow	db 'D_3DNOW',0
aD_sse		db 'D_SSE',0
aD_io		db 'D_IO',0
aD_sys		db 'D_SYS',0
aD_privileged	db 'D_PRIVILEGED',0
aD_avx		db 'D_AVX',0
aD_xop		db 'D_XOP',0
aD_data		db 'D_DATA',0
aD_pseudo	db 'D_PSEUDO',0
aD_prefix	db 'D_PREFIX',0
aS_70		db '!%s|',0
aD_size01	db 'D_SIZE01|',0
aD_postbyte	db 'D_POSTBYTE|',0
aD_longform	db 'D_LONGFORM|',0
aD_data16	db 'D_DATA16|',0
aD_data32	db 'D_DATA32|',0
aD_addr16	db 'D_ADDR16|',0
aD_addr32	db 'D_ADDR32|',0
aD_must66	db 'D_MUST66|',0
aD_mustf2	db 'D_MUSTF2|',0
aD_mustf3	db 'D_MUSTF3|',0
aD_mustnone	db 'D_MUSTNONE|',0
aD_needf2	db 'D_NEEDF2|',0
aD_needf3	db 'D_NEEDF3|',0
aD_norep	db 'D_NOREP|',0
aD_mustrep	db 'D_MUSTREP|',0
aD_mustrepe	db 'D_MUSTREPE|',0
aD_mustrepne	db 'D_MUSTREPNE|',0
aD_lockable	db 'D_LOCKABLE|',0
aD_bhint	db 'D_BHINT|',0
aD_memory	db 'D_MEMORY|',0
aD_register	db 'D_REGISTER|',0
aD_allflags	db 'D_ALLFLAGS|',0
aD_flagz	db 'D_FLAGZ|',0
aD_flagc	db 'D_FLAGC|',0
aD_flagsco	db 'D_FLAGSCO|',0
aD_flagd	db 'D_FLAGD|',0
aD_flagszpc	db 'D_FLAGSZPC|',0
aD_nocflag	db 'D_NOCFLAG|',0
aD_fpupop	db 'D_FPUPOP|',0
aD_fpupop2	db 'D_FPUPOP2|',0
aD_fpupush	db 'D_FPUPUSH|',0
aD_chgesp	db 'D_CHGESP|',0
aD_hladir	db 'D_HLADIR|',0
aD_wildcard	db 'D_WILDCARD|',0
aD_cond		db 'D_COND|',0
aD_usescarry	db 'D_USESCARRY|',0
aD_rare		db 'D_RARE|',0
aD_suspicious	db 'D_SUSPICIOUS|',0
aD_undoc	db 'D_UNDOC|',0
aS_71		db '        !%s, ',0
aDx_je		db 'DX_JE|',0
aDx_jz		db 'DX_JZ|',0
aDx_jb		db 'DX_JB|',0
aDx_jc		db 'DX_JC|',0
aDx_retn	db 'DX_RETN|',0
aDx_vex		db 'DX_VEX|',0
aDx_lshort	db 'DX_LSHORT|',0
aDx_lboth	db 'DX_LBOTH|',0
aDx_llong	db 'DX_LLONG|',0
aDx_ignorel	db 'DX_IGNOREL|',0
aDx_novreg	db 'DX_NOVREG|',0
aDx_w0		db 'DX_W0|',0
aDx_w1		db 'DX_W1|',0
aDx_lead38	db 'DX_LEAD38|',0
aDx_lead3a	db 'DX_LEAD3A|',0
aDx_add		db 'DX_ADD|',0
aDx_sub		db 'DX_SUB|',0
aDx_lea		db 'DX_LEA|',0
aDx_nop		db 'DX_NOP|',0
aS_72		db '!%s,',0Ah,0
aI0x08x0x08x0x0	db '        !%i, 0x!%08X, 0x!%08X, 0x!%02X,',0Ah,0
aB_none		db 'B_NONE',0
aB_al		db 'B_AL',0
aB_ah		db 'B_AH',0
aB_ax		db 'B_AX',0
aB_cl		db 'B_CL',0
aB_cx		db 'B_CX',0
aB_dx		db 'B_DX',0
aB_dxport	db 'B_DXPORT',0
aB_eax		db 'B_EAX',0
aB_ebx		db 'B_EBX',0
aB_ecx		db 'B_ECX',0
aB_edx		db 'B_EDX',0
aB_acc		db 'B_ACC',0
aB_strcnt	db 'B_STRCNT',0
aB_dxedx	db 'B_DXEDX',0
aB_bpebp	db 'B_BPEBP',0
aB_reg		db 'B_REG',0
aB_reg16	db 'B_REG16',0
aB_reg32	db 'B_REG32',0
aB_regcmd	db 'B_REGCMD',0
aB_regcmd8	db 'B_REGCMD8',0
aB_anyreg	db 'B_ANYREG',0
aB_int		db 'B_INT',0
aB_int8		db 'B_INT8',0
aB_int16	db 'B_INT16',0
aB_int32	db 'B_INT32',0
aB_int1632	db 'B_INT1632',0
aB_int64	db 'B_INT64',0
aB_int128	db 'B_INT128',0
aB_immint	db 'B_IMMINT',0
aB_intpair	db 'B_INTPAIR',0
aB_segoffs	db 'B_SEGOFFS',0
aB_strdest	db 'B_STRDEST',0
aB_strdest8	db 'B_STRDEST8',0
aB_strsrc	db 'B_STRSRC',0
aB_strsrc8	db 'B_STRSRC8',0
aB_xlatmem	db 'B_XLATMEM',0
aB_eaxmem	db 'B_EAXMEM',0
aB_longdata	db 'B_LONGDATA',0
aB_anymem	db 'B_ANYMEM',0
aB_stktop	db 'B_STKTOP',0
aB_stktopfar	db 'B_STKTOPFAR',0
aB_stktopefl	db 'B_STKTOPEFL',0
aB_stktopa	db 'B_STKTOPA',0
aB_push		db 'B_PUSH',0
aB_pushret	db 'B_PUSHRET',0
aB_pushretf	db 'B_PUSHRETF',0
aB_pusha	db 'B_PUSHA',0
aB_ebpmem	db 'B_EBPMEM',0
aB_seg		db 'B_SEG',0
aB_segnocs	db 'B_SEGNOCS',0
aB_segcs	db 'B_SEGCS',0
aB_segds	db 'B_SEGDS',0
aB_seges	db 'B_SEGES',0
aB_segfs	db 'B_SEGFS',0
aB_seggs	db 'B_SEGGS',0
aB_segss	db 'B_SEGSS',0
aB_st		db 'B_ST',0
aB_st0		db 'B_ST0',0
aB_st1		db 'B_ST1',0
aB_float32	db 'B_FLOAT32',0
aB_float64	db 'B_FLOAT64',0
aB_float80	db 'B_FLOAT80',0
aB_bcd		db 'B_BCD',0
aB_mreg8x8	db 'B_MREG8x8',0
aB_mmx8x8	db 'B_MMX8x8',0
aB_mmx8x8di	db 'B_MMX8x8DI',0
aB_mreg16x4	db 'B_MREG16x4',0
aB_mmx16x4	db 'B_MMX16x4',0
aB_mreg32x2	db 'B_MREG32x2',0
aB_mmx32x2	db 'B_MMX32x2',0
aB_mreg64	db 'B_MREG64',0
aB_mmx64	db 'B_MMX64',0
aB_3dreg	db 'B_3DREG',0
aB_3dnow	db 'B_3DNOW',0
aB_xmm0i32x4	db 'B_XMM0I32x4',0
aB_xmm0i64x2	db 'B_XMM0I64x2',0
aB_xmm0i8x16	db 'B_XMM0I8x16',0
aB_sregf32x4	db 'B_SREGF32x4',0
aB_sregf32l	db 'B_SREGF32L',0
aB_sregf32x2l	db 'B_SREGF32x2L',0
aB_ssef32x4	db 'B_SSEF32x4',0
aB_ssef32l	db 'B_SSEF32L',0
aB_ssef32x2l	db 'B_SSEF32x2L',0
aB_sregf64x2	db 'B_SREGF64x2',0
aB_sregf64l	db 'B_SREGF64L',0
aB_ssef64x2	db 'B_SSEF64x2',0
aB_ssef64l	db 'B_SSEF64L',0
aB_sregi8x16	db 'B_SREGI8x16',0
aB_ssei8x16	db 'B_SSEI8x16',0
aB_ssei8x16di	db 'B_SSEI8x16DI',0
aB_ssei8x8l	db 'B_SSEI8x8L',0
aB_ssei8x4l	db 'B_SSEI8x4L',0
aB_ssei8x2l	db 'B_SSEI8x2L',0
aB_sregi16x8	db 'B_SREGI16x8',0
aB_ssei16x8	db 'B_SSEI16x8',0
aB_ssei16x4l	db 'B_SSEI16x4L',0
aB_ssei16x2l	db 'B_SSEI16x2L',0
aB_sregi32x4	db 'B_SREGI32x4',0
aB_sregi32l	db 'B_SREGI32L',0
aB_sregi32x2l	db 'B_SREGI32x2L',0
aB_ssei32x4	db 'B_SSEI32x4',0
aB_ssei32x2l	db 'B_SSEI32x2L',0
aB_sregi64x2	db 'B_SREGI64x2',0
aB_ssei64x2	db 'B_SSEI64x2',0
aB_sregi64l	db 'B_SREGI64L',0
aB_efl		db 'B_EFL',0
aB_flags8	db 'B_FLAGS8',0
aB_offset	db 'B_OFFSET',0
aB_byteoffs	db 'B_BYTEOFFS',0
aB_farconst	db 'B_FARCONST',0
aB_descr	db 'B_DESCR',0
aB_1_0		db 'B_1',0
aB_const8	db 'B_CONST8',0
aB_const8_2	db 'B_CONST8_2',0
aB_const16	db 'B_CONST16',0
aB_const	db 'B_CONST',0
aB_constl	db 'B_CONSTL',0
aB_sxtconst	db 'B_SXTCONST',0
aB_cr		db 'B_CR',0
aB_cr0		db 'B_CR0',0
aB_dr		db 'B_DR',0
aB_fst		db 'B_FST',0
aB_fcw		db 'B_FCW',0
aB_mxcsr	db 'B_MXCSR',0
aB_svexf32x4	db 'B_SVEXF32x4',0
aB_svexf32l	db 'B_SVEXF32L',0
aB_svexf64x2	db 'B_SVEXF64x2',0
aB_svexf64l	db 'B_SVEXF64L',0
aB_svexi8x16	db 'B_SVEXI8x16',0
aB_svexi16x8	db 'B_SVEXI16x8',0
aB_svexi32x4	db 'B_SVEXI32x4',0
aB_svexi64x2	db 'B_SVEXI64x2',0
aB_simmi8x16	db 'B_SIMMI8x16',0
a_unkown_6		db '???',0
aB_unsigned	db 'B_UNSIGNED',0
aB_signed	db 'B_SIGNED',0
aB_binary	db 'B_BINARY',0
aB_bitcnt	db 'B_BITCNT',0
aB_shiftcnt	db 'B_SHIFTCNT',0
aB_count	db 'B_COUNT',0
aB_noaddr	db 'B_NOADDR',0
aB_jmpcall	db 'B_JMPCALL',0
aB_jmpcallfar	db 'B_JMPCALLFAR',0
aB_stackinc	db 'B_STACKINC',0
aB_port		db 'B_PORT',0
aB_memory	db 'B_MEMORY|',0
aB_register	db 'B_REGISTER|',0
aB_memonly	db 'B_MEMONLY|',0
aB_regonly	db 'B_REGONLY|',0
aB_32bitonly	db 'B_32BITONLY|',0
aB_noesp	db 'B_NOESP|',0
aB_novexsize	db 'B_NOVEXSIZE|',0
aB_showsize	db 'B_SHOWSIZE|',0
aB_chg		db 'B_CHG|',0
aB_upd		db 'B_UPD|',0
aB_pseudo	db 'B_PSEUDO|',0
aB_noseg	db 'B_NOSEG|',0
aSS_2		db '        !%s!%s',0Ah,0
		db ' },',0
aNull00		db 0Ah
		db '  { NULL,',0Ah
		db '        0, 0,',0Ah,0
a00x000000000x0	db '        0, 0x00000000, 0x00000000, 0x00,',0Ah,0
aB_noneB_none	db '        B_NONE,',0Ah
		db '        B_NONE,',0Ah,0
aB_noneB_none_0	db '        B_NONE,',0Ah
		db '        B_NONE',0Ah
		db '  }',0Ah
		db 0Ah
		db '};',0Ah,0

_data		ends
		